### ISSUE TITLE
deploying the docker compose creates a lot of activity which maybe can be optimised by using canned images

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/geopython-workshop#73]
use images on the docker compose which are prepared for the workshop:
- skip non-used libraries
- update the images to latest version of ubuntu libraries etc.
- do not build source code on deploy time

this issue is used to research possibilities here

**Comment by pvgenuchten** [comment]
if pygeoapi is removed from the workshop, we can have 2 docker compose, one with and one without pygeoapi

**Comment by justb4** [comment]
@pvgenuchten what are "canned images"? The workshop's Docker Image is already auto-published to DockerHub, so participants don't need to build the image. But still the Image is big: about 1GB. One way to make it smaller is to use a (Ubuntu/Debian) 'slim' base image and staged builds (only copy the build results into a fresh Ubuntu base image). The latter will take some hours of tweaking as to determine which files to copy.  Or is that what you mean with 'canned images'. We have a similar size problem with pygeoapi, that is mainly due to GDAL dep. Using `Alpine` images is 'out' these days.

**Comment by pvgenuchten** [comment]
Thanx for your thoughts @justb4, the canned word was mentioned on the meeting, not exactly sure what it is, I imagine no installations at deploy time.

**Comment by pvgenuchten** [comment]
i had no time to research this, closing
